# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/dsp_macro/dsp_macro.xci
# IP: The module: 'dsp_macro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.gen/sources_1/ip/dsp_macro/dsp_macro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/dsp_macro/dsp_macro.xci
# IP: The module: 'dsp_macro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.gen/sources_1/ip/dsp_macro/dsp_macro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
