#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jun 01 20:48:26 CST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_kaReduced_behav -key {Behavioral:sim_1:Functional:tb_kaReduced} -tclbatch tb_kaReduced.tcl -view /home/hydrangea/project/AMD/karatsuba/karatsuba/ka256_tb_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_long_adder_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_kaExt_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_kaReduced_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_blkram_behav.wcfg -log simulate.log"
xsim tb_kaReduced_behav -key {Behavioral:sim_1:Functional:tb_kaReduced} -tclbatch tb_kaReduced.tcl -view /home/hydrangea/project/AMD/karatsuba/karatsuba/ka256_tb_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_long_adder_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_kaExt_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_kaReduced_behav.wcfg -view /home/hydrangea/project/AMD/karatsuba/karatsuba/tb_blkram_behav.wcfg -log simulate.log

