# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/1.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_util_reduced_logic_0_0/top_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_reduced_logic_0_0 || ORIG_REF_NAME==top_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_0_0/top_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_0_0 || ORIG_REF_NAME==top_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/top/ip/top_util_reduced_logic_1_0/top_util_reduced_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_reduced_logic_1_0 || ORIG_REF_NAME==top_util_reduced_logic_1_0} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_0_1/top_c_counter_binary_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_0_1 || ORIG_REF_NAME==top_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_1_0/top_c_counter_binary_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_1_0 || ORIG_REF_NAME==top_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_1_1/top_c_counter_binary_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_1_1 || ORIG_REF_NAME==top_c_counter_binary_1_1} -quiet] -quiet

# IP: bd/top/ip/top_wire_conn_0_0/top_wire_conn_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_wire_conn_0_0 || ORIG_REF_NAME==top_wire_conn_0_0} -quiet] -quiet

# IP: bd/top/ip/top_kaReduced128_0_0/top_kaReduced128_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_kaReduced128_0_0 || ORIG_REF_NAME==top_kaReduced128_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/dsp_macro/dsp_macro.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro || ORIG_REF_NAME==dsp_macro} -quiet] -quiet

# XDC: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.gen/sources_1/bd/top/top_ooc.xdc
