# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/bd/top/ip/top_kaReduced128_0_0/top_kaReduced128_0_0.xci
# IP: The module: 'top_kaReduced128_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/dsp_macro/dsp_macro.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro || ORIG_REF_NAME==dsp_macro} -quiet] -quiet

# XDC: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.gen/sources_1/bd/top/ip/top_kaReduced128_0_0/top_kaReduced128_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_kaReduced128_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/bd/top/ip/top_kaReduced128_0_0/top_kaReduced128_0_0.xci
# IP: The module: 'top_kaReduced128_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.srcs/sources_1/ip/dsp_macro/dsp_macro.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro || ORIG_REF_NAME==dsp_macro} -quiet] -quiet

# XDC: /home/hydrangea/project/AMD/karatsuba/karatsuba/karatsuba.gen/sources_1/bd/top/ip/top_kaReduced128_0_0/top_kaReduced128_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_kaReduced128_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
